---
site_name: AutoMAxO

theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: white
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue
      accent: white
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  language: en

plugins:
  - search

nav:
  - Tutorial: tutorial.md
  - Installation: install.md
  - Data: data.md

site_url: https://monarch-initiative.github.io/automaxo/
repo_url: https://github.com/monarch-initiative/automaxo/

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables

copyright: |
  &copy; 2024 <a href="https://github.com/pnrobinson"  target="_blank" rel="noopener">Peter N Robinson</a>